driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.0.3

platforms:
  - name: ubuntu-14.04
    driver:
      username: vagrant
      box: ubuntu-1404
      box_url: 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
      network:
        - ["private_network", {ip: "192.168.33.36"}]

suites:
  - name: default
    run_list: 
      - 'recipe[stripe-ctf::default]'
